spring:
  datasource:
    password: 1234567
    url: jdbc:postgresql://localhost:5432/dsdeliver
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
